# Generated by Django 5.0.3 on 2024-04-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_ml_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='job_title',
            field=models.CharField(max_length=150),
        ),
    ]
