# Generated by Django 5.0.3 on 2024-04-11 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_job_post_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_post',
            name='job_title',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='ml_record',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
